name: Go Lint
#
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
#
